# Generated by Django 4.1 on 2022-10-10 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_zircategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='zir_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.zircategory'),
        ),
    ]
