# Generated by Django 4.0.4 on 2022-10-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_zir_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(unique=True, upload_to='', verbose_name='عکس محصول'),
        ),
    ]
