# Generated by Django 4.1 on 2022-10-09 23:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterAsli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NavOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم صاحب سایت')),
                ('logo', models.FileField(null=True, upload_to='', verbose_name='لوگو')),
                ('alt', models.CharField(max_length=100, null=True, verbose_name='توضیحات لوگو')),
                ('favicon', models.FileField(null=True, upload_to='', verbose_name='آیکون')),
                ('alt2', models.CharField(max_length=100, null=True, verbose_name='توضیحات icon')),
                ('text', models.CharField(max_length=500, null=True, verbose_name='متن')),
                ('text_products_view', models.CharField(max_length=100, null=True, verbose_name='متن بالای تبلیغ')),
                ('telephon', models.CharField(max_length=30, null=True, verbose_name='تلفن')),
                ('link_products_view', models.CharField(max_length=100, null=True, verbose_name='لینک بالای تبلیغ')),
                ('footer_text', models.CharField(max_length=300, null=True)),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='ایمیل')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='ادرس')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False, verbose_name='نمایش داده شود؟')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=300, null=True, verbose_name='متن ساده')),
                ('text2', models.CharField(max_length=300, null=True, verbose_name='متن بولد')),
                ('text3', models.CharField(max_length=300, null=True, verbose_name='متن قیمت')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس سلایدر')),
                ('alt', models.CharField(max_length=100, verbose_name='توضیح عکس')),
                ('name_button', models.CharField(max_length=100, null=True, verbose_name='متن دکمه')),
                ('link', models.CharField(max_length=100, null=True, verbose_name='ادرس دکمه')),
            ],
        ),
        migrations.CreateModel(
            name='Tabligh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name_button', models.CharField(max_length=100, null=True, verbose_name='متن دکمه')),
                ('link', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='TagNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='تگ ها')),
            ],
        ),
        migrations.CreateModel(
            name='TagNewPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='تگ ها')),
            ],
        ),
        migrations.CreateModel(
            name='ZirSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='')),
                ('text1', models.CharField(max_length=100)),
                ('name_button1', models.CharField(max_length=100, null=True, verbose_name='متن دکمه')),
                ('link1', models.CharField(max_length=100, null=True, verbose_name='ادرس صفحه')),
                ('image2', models.ImageField(upload_to='')),
                ('text2', models.CharField(max_length=100)),
                ('name_button2', models.CharField(max_length=100, null=True, verbose_name='متن دکمه')),
                ('link2', models.CharField(max_length=100, null=True, verbose_name='ادرس صفحه')),
                ('image3', models.ImageField(upload_to='')),
                ('text3', models.CharField(max_length=100)),
                ('name_button3', models.CharField(max_length=100, null=True, verbose_name='متن دکمه')),
                ('link3', models.CharField(max_length=100, null=True, verbose_name='ادرس صفحه')),
                ('image4', models.ImageField(upload_to='')),
                ('text4', models.CharField(max_length=100)),
                ('name_button4', models.CharField(max_length=100, null=True, verbose_name='متن دکمه')),
                ('link4', models.CharField(max_length=100, null=True, verbose_name='ادرس صفحه')),
            ],
        ),
        migrations.CreateModel(
            name='NavTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.navone')),
            ],
        ),
        migrations.CreateModel(
            name='NavThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='ادرس صفحه')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.navtwo')),
            ],
        ),
        migrations.CreateModel(
            name='FooterZir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('link', models.CharField(max_length=100, null=True, verbose_name='لینک صفحه')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='بدنه')),
                ('url_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='نام صفحه')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.footerasli')),
                ('tag', models.ManyToManyField(to='home.tagfooter', verbose_name='تگ های فوتر')),
            ],
        ),
    ]
